version = 0.1

[default.deploy.parameters]
stack_name = "mining-stock-app"
resolve_s3 = true
s3_prefix = "mining-stock-app"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
